; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-s3-devkitc-1-release

[env:esp32-s3-devkitc-1]
platform = espressif32
board = crowpanel_advance_7
framework = espidf
board_build.sdkconfig = sdkconfig.esp32-s3-devkitc-1
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions_16mb_ota.csv
build_type = debug
build_unflags =
  -flto

build_flags =
  -DBOARD_HAS_PSRAM
  -O1
  -fno-tree-slp-vectorize
  -DCT_TOUCH_ENABLED=1
  -DCT_TOUCH_INT_GPIO=1
  -DCT_TOUCH_USE_INT=0
  -DCT_TOUCH_LOG=0
  -DCT_TOUCH_REG_ADDR_SWAP=0
  -DCT_TOUCH_CAL_X_MIN=2
  -DCT_TOUCH_CAL_X_MAX=793
  -DCT_TOUCH_CAL_Y_MIN=1
  -DCT_TOUCH_CAL_Y_MAX=481
  -DCT_TOUCH_FORCE_DEFAULTS=0
  -DCT_TOUCH_OFFSET_X=-3
  -DCT_TOUCH_OFFSET_Y=0
  -DCT_TOUCH_PHYS_V_RES=480
  -DCT_TOUCH_TARGET_V_RES=480
  -DCONFIG_ESP_LCD_TOUCH_MAX_POINTS=1
  -DCT_LVGL_ENABLE=1
  -DCT_SCHEDULER_ENABLE=1
  -DCT_WIFI_ENABLE=1
  -DCT_UI_MINIMAL=0
  -DCT_KEYBOARD_ENABLE=1
  -DCT_UI_DISABLE=0
  -DCT_UI_TOUCH_DEBUG=0
  -DCT_UI_BORDER_DEBUG=0
  -DCT_LVGL_TASK_ENABLE=1
  -DCT_LVGL_DRY_RUN=0
  -DCT_LVGL_TASK_TICK=1
  -DCT_LVGL_HANDLER_ENABLE=1
  -DCT_LVGL_HANDLER_IN_TASK=1
  -DCT_LVGL_SKIP_DISPLAY=0
  -DCT_LVGL_DUMMY_DISPLAY=0
  -DCT_LVGL_PAUSE_REFR_TIMER=0
  -DCT_SPARKLINE_ENABLE=0
  -DCT_BUILD_BRANCH_STR=\"v1.0-test\"
  -DCT_CMC_API_KEY=\"d6c432dea1eb44c28429ae84c26a469f\"
  -DLV_CONF_INCLUDE_SIMPLE
  -Isrc
  -Icomponents/esp_lcd_touch/include

lib_deps =
  lvgl/lvgl@8.3.11

[env:esp32-s3-devkitc-1-release]
extends = env:esp32-s3-devkitc-1
build_type = release
monitor_filters = default
build_unflags =
  -O1
build_flags =
  ${env:esp32-s3-devkitc-1.build_flags}
  -O2
  -DNDEBUG
